import { StyleSheet, StatusBar } from "react-native";
import theme from "./styles/theme.style.js";

const styles = StyleSheet.create({
  container: {
    paddingTop: StatusBar.currentHeight + 20,
    marginHorizontal: 16,
    flex: 1,
    padding: 10,
  },
  containerLoading: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  containerModal: {
    paddingTop: 200,
    marginHorizontal: 16,
    flex: 1,
    padding: 20,
  },
  body: {
    flex: 1,
  },
  footer: {
    position: "absolute",
    // top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // height: 100,
    marginHorizontal: 70,
    marginVertical: 10,
    paddingHorizontal: 15,
    paddingVertical: 8,
    // borderColor: "black",
    // borderWidth: 2,
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#212121",
    fontSize: 14,
    color: "white",
    // fontWeight: "bold",
    fontFamily: "sans-serif",
  },
  footerCalendar: {
    position: "absolute",
    // top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // height: 100,
    marginHorizontal: 40,
    marginVertical: 10,
    paddingHorizontal: 35,
    paddingVertical: 8,
    // borderColor: "black",
    // borderWidth: 2,
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-start",
    backgroundColor: "#212121",
    fontSize: 14,
    color: "white",
    // fontWeight: "bold",
    fontFamily: "sans-serif",
  },
  dataItem: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    // paddingBottom: 20,
    // paddingTop: 20,
    // // paddingLeft: 20,
    // // paddingRight: 20,
    // // padding:20,
    // borderBottomWidth: 1,
    // borderColor: "grey",
  },
  row: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 15,
    paddingTop: 10,
    // paddingLeft: 20,
    // paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    flexWrap: "wrap",
  },
  textSmall: {
    fontSize: theme.FONT_SIZE_SMALL,
    color: theme.SECONDARY_TEXT_COLOR,
    fontFamily: "sans-serif",
  },
  textLarge: {
    fontSize: theme.FONT_SIZE_MEDIUM,
    color: theme.PRIMARY_TEXT_COLOR,
    fontWeight: "bold",
    fontFamily: "sans-serif",
  },
  picker: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    // paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    flexWrap: "wrap",
  },
  chart: {
    flex: 1,
    backgroundColor: "#121212",
    justifyContent: "center",
    alignItems: "center",
  },
  slider: {
    flexDirection: "column",
    // flex: 1,
    // justifyContent: "space-between",
    // alignItems: "flex-start",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    // flexWrap: "wrap",
  },
  switch: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    // alignItems: "flex-start",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    // flexWrap: "wrap",
  },
  calendarList: {
    width: "100%",
    // height: 340,
    borderBottomWidth: 1,
    borderColor: "#212121",
    alignSelf: "center",
    // paddingHorizontal: 50,
  },
  header: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    // paddingRight: 150,
    marginTop: 10,
    marginBottom: 10,
  },
  month: {
    marginLeft: 5,
  },
  year: {
    marginRight: 5,
  },
});

export { styles };
