import { StyleSheet, StatusBar } from "react-native";

const styles = StyleSheet.create({
  containerLoading: {
    padding: 35,
    marginTop: 150,
  },
  container: {
    paddingTop: StatusBar.currentHeight + 20,
    marginHorizontal: 16,
    flex: 1,
    padding: 10,
  },
  containerModal: {
    paddingTop: 200,
    marginHorizontal: 16,
    flex: 1,
    padding: 20,
  },
  dataItem: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 20,
    paddingTop: 20,
    // paddingLeft: 20,
    // paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "grey",
  },
  text: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    // paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    flexWrap: "wrap",
  },
  textSmall: {
    fontSize: 16,
    color: "#b3b3b3",
    fontFamily: "sans-serif",
  },
  textLarge: {
    fontSize: 18,
    color: "white",
    fontWeight: "bold",
    fontFamily: "sans-serif",
  },
  picker: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    // paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    flexWrap: "wrap",
  },
  chart: {
    // height: "18em",
    flex: 1,
    backgroundColor: "#121212",
    justifyContent: "center",
    alignItems: "center",
  },
  slider: {
    flexDirection: "column",
    // flex: 1,
    // justifyContent: "space-between",
    // alignItems: "flex-start",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    // flexWrap: "wrap",
  },
  switch: {
    flexDirection: "row",
    // flex: 1,
    justifyContent: "space-between",
    // alignItems: "flex-start",
    paddingBottom: 10,
    paddingTop: 10,
    // paddingLeft: 20,
    paddingRight: 20,
    // padding:20,
    borderBottomWidth: 1,
    borderColor: "#212121",
    // flexWrap: "wrap",
  },
  header: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
  },
  month: {
    marginLeft: 5,
  },
  year: {
    marginRight: 5,
  },
});

export { styles };
